### PR TITLE
Search all file extensions other than pd_darwin, pd_linux and dll

### PR DESCRIPTION
**Pull request by tomoyanonymous**
This PR adds the feature that searches external with file types other than `pd_darwin`, `pd_linux`, and `dll`.

According to https://github.com/pure-data/externals-howto#library , external files can be architecture-specific and they will be distinguished by file extensions.
In fact, external objects in `else` library for macOS are shipped with `*.d_fat` and they could not be found with the current completion.

Currently tested only on macOS but I think it will work on other OSs...

### CODE REVIEW

**Comment by porres** [comment]
hi, this project seems a bit dead to me :) I could release a new version in my fork and take this

**Comment by porres** [comment]
uploaded a new version here https://github.com/porres/completion-plugin

@tomoyanonymous I hope you can help me with more improvements. Like, now if we scan for ELSE externals we get two equal entries for sfont~ because there are two separate binaries one for each architecture, hence, this change of yours may lead to duplicate names and we need a way to filter these repetitions.

**Comment by tomoyanonymous** [comment]
@porres 
Thanks for forking the project. I just found the way to solve the duplication problem with a tiny fix. I'll send PR to your repo soon.

**Comment by porres** [comment]
>  I'll send PR to your repo soo

great, I guess I should create a new repo from scratch and you can fork from me :)

**Pull request closed without merging**
